#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

# Use Marathon provided port if HTTPPORT is not set by user:
[ "${PORT0}" ] && [ ! "${HTTPPORT}" ] && HTTPPORT=${PORT0}

# Set the Mesos master:
MESOS_MASTER="${MESOS_MASTER:-'zk://zk1:2181,zk2:2181,zk3:2181/mesos'}" && \
sed -i "s#XXX-MESOS_MASTER-XXX#${MESOS_MASTER}#" /var/lib/jenkins/config.xml

# Set the Mesos framework name:
MESOS_FRAMEWORK_NAME="${MESOS_FRAMEWORK_NAME:-'jenkins'}" && \
sed -i "s/XXX-MESOS_FRAMEWORK_NAME-XXX/${MESOS_FRAMEWORK_NAME}/" /var/lib/jenkins/config.xml

# Set the Jenkins system message:
JENKINS_SYSTEM_MESSAGE="${JENKINS_SYSTEM_MESSAGE:-'Jenkins master'}" && \
sed -i "s/XXX-JENKINS_SYSTEM_MESSAGE-XXX/${JENKINS_SYSTEM_MESSAGE}/" /var/lib/jenkins/config.xml

# Set the Jenkins URL:
JENKINS_URL="http://$(cat /proc/sys/kernel/hostname):${PORT0}" && \
sed -i "s#XXX-JENKINS_URL-XXX#${JENKINS_URL}#" /var/lib/jenkins/config.xml

# Set Jenkins commandline options:
OPTS="
--webroot=${WEBROOT:-'/var/cache/jenkins/war'}
--httpPort=${HTTPPORT:-8080}
--ajp13Port=${AJP13PORT:-8009}
--debug=${DEBUG:-5}
--handlerCountMax=${HANDLERCOUNTMAX:-100}
--handlerCountMaxIdle=${HANDLERCOUNTMAXIDLE:-20}"

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $* ${OPTS}"
exec $* ${OPTS}
