#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

# Use Marathon provided port if HTTPPORT is not set by user:
[ "${PORT0}" ] && [ ! "${HTTPPORT}" ] && HTTPPORT=${PORT0}

OPTS="
--webroot=${WEBROOT:-'/var/cache/jenkins/war'}
--httpPort=${HTTPPORT:-8080}
--ajp13Port=${AJP13PORT:-8009}
--debug=${DEBUG:-5}
--handlerCountMax=${HANDLERCOUNTMAX:-100}
--handlerCountMaxIdle=${HANDLERCOUNTMAXIDLE:-20}"

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $* ${OPTS}"
exec $* ${OPTS}
